
- name: Demo on vars usage                         #play name   
  hosts: all                                        #which includes everthing in inv file
  vars:                                             #Global variables:all the tasks of this play can access this variable
    URL: play.google.com 
  vars_files:
    - "{{ENV}}.yml"
  vars_prompt:
    - name: URNAME
      prompt: Enter your name 
      private: false                               #by default promt variables are used for secrets  
  tasks:
    - name: printing the variable                  #task1 name
      ansible.builtin.debug:
        msg: value of the URL is {{URL}}

    - name: Demo on using local variable            #task2 name            #imp: no two tasks should have the same name"
      ansible.builtin.debug:
        msg: value of the URL's {{URL}}
      vars:
        URL: task.google.com
   # - name: Demo on using undeclared variable       task3 name
     # ansible.builtin.debug:
       #   msg: value of the URL's {{CLIURL}}

    # - name: printing promt variable                # task4 name
    #   ansible.builtin.debug:
    #     msg: name of the person is {{URNAME}}

    - name: This is env specific                        #task5 name
      ansible.builtin.debug:
        msg: Type of instance to be used  {{INS_TYPE}}


# If you try to print a variable which is not declared it os going to through you an error
#There are certain condition you are not sure about the value of a variable--then how can you supply it from the command line????
#ans::: we nee to pass it from the command line    

# note: if you want to print a variable the enclose the variable in  "{{varname}}" and there is no concept of single quotes
#If the variables is present in between the string of words ,you dont have toenclose them in quotes.


### Variable prcedence:(***vimp***)
# Command line variable(cli) >local variables >globalvriables
#When compared to the globalvariables localvariables have highest precedence when compared to the local variables cli varibles will have highest precedence

