
- name: Demo on vars usage       
  hosts: all 
  vars:                         #Global variables:all the tasks of this ppay can access this variable
    URL: play.google.com 
  vars_prompt:
    - name: URNAME
      promt: Enter your name      
  tasks:
    - name: printing the variable
      ansible.builtin.debug:
        msg: value of the URL is {{URL}}

    - name: Demo on using local variables                #imp: no two tasks should have the same name"
      ansible.builtin.debug:
        msg: value of the URL's {{URL}}
      vars:
        URL: task.google.com
     - name: Demo on using undeclared variable
       ansible.builtin.debug:
           msg: value of the URL's {{CLIURL}}

    - name: printing promt variable
      ansible.builtin.debug:
        msg: name of the person is {{URNAME}}


# If you try to print a variable which is not declared it os going to through you an error
#There are certain condition you are not sure about the value of a variable--then how can you supply it from the command line????
#ans::: we nee to pass it from the command line    

# note: if you want to print a variable the enclose the variable in  "{{varname}}" and there is no concept of single quotes
#If the variables is present in between the string of words ,you dont have toenclose them in quotes.


### Variable prcedence:(***vimp***)
# Command line variable(cli) >local variables >globalvriables
#When compared to the globalvariables localvariables have highest precedence when compared to the local variables cli varibles will have highest precedence

