
- name: Demo on facts                        #play name   
  hosts: all  
  #gather_facts: no                              #which includes everthing in inv file                  
  tasks:
    - name: printing the default  variable         
      ansible.builtin.debug:
        msg: server falvour is "{{ansible_distribution}}" 
        
    - name: printing the Mac address       
      ansible.builtin.debug:
        msg: Mac address of the node is  "{{ansible_default_ipv4.macaddress}}"            #even if you dont mention quotes""" also it will work


### facts are nothing but a properties which will act as a predefined variable" that is why we have not declared variable here"

   