
- name: Demo on shell                        #play name   
  hosts: all                                 #which includes everthing in inv file
  #gather_facts: no                          #if you dont needs facts to be gathered then ,then we can mention this as no              
  tasks:
    - name: Running uptime command         
      ansible.builtin.shell: uptime
      register: OUT                       #shell module is going to run the commnd but will not show you the output
                                            #so we need to store that output,here register is a key word whre we register the output
                                            #in the variable called as OUT and can use it whenever we want,the variable name need not to be an "out" it cn be something ele also
    - name: printing the uptime         
      ansible.builtin.debug: 
       msg: "{{OUT.stdout}}"
      
    - name: Declaring the variable         
      set_fact: 
       EXITCODE: "{{OUT.rc}}"

         
    - name: Printing the uptime exit code
      ansible.builtin.debug:     
       msg: uptime exit code is "{{EXITCODE}}"

  