
- name: Demo on shell                        #play name   
  hosts: all                                 #which includes everthing in inv file
  #gather_facts: no                          #if you dont needs facts to be gathered then ,then we can mention this as no              
  tasks:
    - name: Running uptime command         
      ansible.builtin.shell: uptime
      register: OUT

    - name: printing the uptime         
      ansible.builtin.debug: 
       msg: "{{OUT.stdout}}"
      
    - name: Declaring the variable         
      set_fact: 
       EXITCODE: "{{OUT.rc}}"

         
    - name: Printing the uptime exit code
      ansible.builtin.debug:     
       msg: uptime exit code is "{{EXITCODE}}"

  