#"If any task fail in the playbook the sub-sequent task will be failed and playbook will be "executed"

- name: Demo on errors
  hosts: all
  tasks:
   - name: check tomcat is running or not
     ansible.builtin.shell: ps -ef | grep java | grep -v grep
     register: OUT
     ignore_errors: yes         #ignore_errors is a key word irrespective of task is failed it will proceed with the next task


   - name: starting tomcat
     ansible.builtin.debug:
       msg: tomcat is started 