- name: Demo on conditions
  hosts: all
  vars:
    action: true
  tasks:
    - name: Run this only when the system distribution is CentOS
      ansible.builtin.debug:
        msg: Welcome to {{ansible_distribution}}
      when: ansible_distribution == "CentOS"


    - name: Run this only when the system distribution is Ubuntu
      ansible.builtin.debug:
        msg: Welcome to {{ansible_distribution}}
      when: ansible_distribution == "Ubuntu"  

    - name: Run this action
      ansible.builtin.debug:
        msg: Action is true
      when: action   
  














## Older versions of ansible uses undefined, #latest version of ansible users not defined 
# defined , not defined, true, false , succeded , failure all of them are predefined keywords as per the documentation 
# Ref : https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_conditionals.html