- name: Demo on  Privilege user
  hosts: all
  become: yes                     #privilige escalation :runs the playbook as a root user
  tasks:
   
   - name: checking the user ID
     ansible.builtin.shell: id
     register: OUT            #here we are registering the out put of a shellcommand we are storing it in a variable called OUT

   - name: printing the user details
     ansible.builtin.debug:
        msg: "{{OUT.stdout}}"       #HERE WE ARE PRINTING THE VARIABLE OUT


  