- name: Demo on  Privilege user
  hosts: all
  tasks:
   - name: checking the user ID
     ansible.builtin.shell: id
     register: OUT

   - name: printing the user details
     ansible.builtin.debug:
       msg: "{{OUT}}"