- name: Demo on loops
  hosts: all
  tasks:
   - name: Demo on using loops
     ansible.builtin.debug:
       msg: "value of {{item}}"         #item is a keyword to represent the values in the list
     loop: 
      - 100
      - 200
      - 300
      - 400