- name: Demo on copy
  hosts: all
  become: yes
  tasks:
   - name: copying the file
     ansible.builtin.copy:
       src: systemd.service                                                    #file name
       dest: /home/centos/systemd.service